spring.application.name=ancoregaming
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.security.user.name=${SECURITY_NAME}
spring.security.user.password=${SECURITY_PASS}
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
jwt.refresh-token.expiration=604800000
CLOUDINARY_URL=${CLOUDINARY_URL}
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
stripe.public.key=${STRIPE_PUBLIC_KEY}
stripe.api.key=${STRIPE_API_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_KEY}
email.password=${SMTP_PASS}
email.username=${SMTP_USER}